#!/usr/bin/env bash
# Forge — `dora-roi-helper.sh` DORA Register-of-Information submission helper
# Audit: B.6.9 (b6-9-compliance)
#
# Helps an adopter of the `event-driven-eu` archetype compile the DORA
# Register of Information (RoI) ICT third-party register entries relevant to
# this archetype's stack. It DRIVES (reads, never forks) the b7-5 base
# template `.forge/compliance/dora/roi-register.template.yaml` and specialises
# it for the event-driven-eu ICT third-party provider categories grounded in
# `.forge/schemas/event-driven-eu/1.0.0.yaml` `components:` :
#
#   - NATS JetStream  (event-backbone)
#   - Temporal        (orchestration)
#   - Postgres        (event-store)
#
# The RoI ESA submission deadline "30 avr 2026" is grounded verbatim in
# `docs/ARCHITECTURE-TARGET.md` §10.4. The authoritative ESA field schema is a
# Themis (K.5) Phase-B determination, carried as a [NEEDS CLARIFICATION] marker
# — this helper emits a STARTING STRUCTURE only, never a legally authoritative
# field list (Article III.4).
#
# Usage :
#   bash .forge/scripts/compliance/dora-roi-helper.sh \
#     [--output <path>] [--target <dir>]
#
# Defaults : --output stdout, --target $(pwd).
#
# Exit codes :
#   0 — RoI skeleton written
#   1 — missing base template at the target
#   2 — usage error (bad args, target not a directory)
#
# Pattern : bash thin + Python 3 inline (mirrors `bundle.sh` / `bin/forge-sbom.sh`).

set -uo pipefail

OUTPUT="-"
TARGET="$(pwd)"

err() { echo "forge-dora-roi: $*" >&2; }

usage() {
  cat <<EOF
Usage: dora-roi-helper.sh [--output <path>] [--target <dir>]

Emits a DORA Register-of-Information skeleton for the event-driven-eu ICT
third-party stack (NATS JetStream / Temporal / Postgres), driving the b7-5
base template .forge/compliance/dora/roi-register.template.yaml.

Defaults : --output stdout ('-'), --target \$(pwd).
Exit codes : 0 success / 1 missing base template / 2 usage error.
EOF
}

while [ $# -gt 0 ]; do
  case "$1" in
    --output) OUTPUT="${2:-}"; shift 2 ;;
    --output=*) OUTPUT="${1#*=}"; shift ;;
    --target) TARGET="${2:-}"; shift 2 ;;
    --target=*) TARGET="${1#*=}"; shift ;;
    --help|-h) usage; exit 0 ;;
    *) err "unknown argument: $1"; usage >&2; exit 2 ;;
  esac
done

if [ ! -d "$TARGET" ]; then
  err "target directory not found: $TARGET"; exit 2
fi
TARGET="$(cd "$TARGET" && pwd)"

BASE_TEMPLATE="$TARGET/.forge/compliance/dora/roi-register.template.yaml"
if [ ! -f "$BASE_TEMPLATE" ]; then
  err "missing base template: $BASE_TEMPLATE (b7-5 dora RoI base required)"; exit 1
fi

# Resolve OUTPUT to absolute unless stdout.
if [ "$OUTPUT" != "-" ]; then
  case "$OUTPUT" in
    /*) ;;
    *) OUTPUT="$(pwd)/$OUTPUT" ;;
  esac
fi

python3 - "$BASE_TEMPLATE" "$OUTPUT" <<'PY'
import sys

base_path = sys.argv[1]
output_path = sys.argv[2]

# DRIVE (read, never fork) the b7-5 base RoI template — confirm it is present
# and grounds the schema_version so the specialised output stays consistent.
with open(base_path) as f:
    base = f.read()

# event-driven-eu ICT third-party provider categories, grounded in
# .forge/schemas/event-driven-eu/1.0.0.yaml components:.
providers = [
    ("NATS JetStream", "event-backbone (pub/sub, streams, consumers)"),
    ("Temporal", "orchestration (durable workflows / saga workers)"),
    ("Postgres", "event-store (append-only events + projections)"),
]

lines = []
lines.append("# Audit: B.6.9 (b6-9-compliance)")
lines.append("# DORA Register of Information (RoI) — event-driven-eu ICT third-party")
lines.append("# register. Generated by .forge/scripts/compliance/dora-roi-helper.sh,")
lines.append("# driving the b7-5 base .forge/compliance/dora/roi-register.template.yaml.")
lines.append("#")
lines.append("# The RoI ESA submission deadline is grounded verbatim: 30 avr 2026")
lines.append("# (docs/ARCHITECTURE-TARGET.md §10.4).")
lines.append("#")
lines.append("# needs_clarification: >-")
lines.append("#   [NEEDS CLARIFICATION: the authoritative DORA Register-of-Information")
lines.append("#   field schema (the mandatory ESA-prescribed templates / fields) —")
lines.append("#   Themis (K.5) to supply from the official DORA text; the entries below")
lines.append("#   are an adopter-fillable starting structure scoped to the event-driven-eu")
lines.append("#   stack, NOT the legally authoritative field list.]")
lines.append("#")
lines.append("# Fill the <FILL: ...> placeholders and submit per your competent authority.")
lines.append('schema_version: "1.0.0"')
lines.append("register_of_information:")
lines.append("  entity:")
lines.append('    name: "<FILL: reporting entity name>"')
lines.append('    identifier: "<FILL: LEI or competent-authority identifier>"')
lines.append("  ict_third_party_providers:")
for name, role in providers:
    lines.append(f'    - provider_name: "<FILL: your {name} provider (e.g. self-host / EU-managed)>"')
    lines.append(f'      component: "{name}"')
    lines.append(f'      role: "{role}"')
    lines.append('      criticality: "<FILL: critical | important | other>"')
    lines.append('      eu_sovereignty_tier: "<FILL: T1 | T2 | T3>"')
lines.append("  submission:")
lines.append('    competent_authority: "<FILL: your ESA / national competent authority>"')
lines.append('    reference_deadline: "30 avr 2026"  # grounded ESA deadline (ARCHITECTURE-TARGET §10.4)')

rendered = "\n".join(lines) + "\n"

if output_path == "-":
    sys.stdout.write(rendered)
else:
    with open(output_path, "w") as f:
        f.write(rendered)
    print(f"forge-dora-roi: wrote {output_path}", file=sys.stderr)

sys.exit(0)
PY
rc=$?
exit $rc
