# <!-- Audit: B.1.2 + B.1.3 + B.1.4 + B.1.13 (b1-scaffolder) -->
# BDD scenarios for the `/forge:init --archetype full-stack-monorepo`
# slash command. These scenarios mirror AC-001..007 from specs.md
# one-to-one. Executed by `.forge/scripts/tests/scaffolder.test.sh`
# across three levels (L1 plan shape, L2 overlay render, L3 E2E with
# flutter + cargo + buf).

Feature: b1-scaffolder — scaffold a full-stack-monorepo project

  As a developer adopting Forge
  I want to scaffold a Flutter + Rust + Infra monorepo in one command
  So that my new project conforms to the archetype contract from day one

  Background:
    Given I have cloned the Forge repository
    And the Forge framework assets (.forge/, .claude/) are intact
    And I have `flutter` >= 3.24 on PATH (when running the L3 happy path)
    And I have `cargo` >= 1.80 on PATH
    And I have `buf` >= 1.30 on PATH

  # ─── AC-001 — happy path ──────────────────────────────────────

  Scenario: AC-001 full scaffold produces a contract-conformant tree
    Given no directory named `demo-app` exists at the target path
    When I run `/forge:init --archetype full-stack-monorepo demo-app --org com.example.forgetest`
    Then a directory `demo-app/` is created
    And `demo-app/frontend/pubspec.yaml` exists (from `flutter create`)
    And `demo-app/backend/Cargo.toml` declares the 5-crate workspace
    And `demo-app/backend/crates/{domain,application,grpc-api,infrastructure}/Cargo.toml` exist
    And `demo-app/backend/bin-server/Cargo.toml` exists
    And `demo-app/shared/protos/v1/example/example.proto` exists
    And `demo-app/Taskfile.yml` exposes `dev`, `test`, `lint`, `proto`, `release`
    And `demo-app/docker-compose.dev.yml` lists services `fsm-db`, `fsm-backend`, `fsm-kong`
    And `demo-app/.forge/scaffold-manifest.yaml` records flutter + cargo + buf versions
    And `bash demo-app/.forge/scripts/validate-foundations.sh` exits 0
    And every line is `PASS: FR-GL-00[1-7] — ...`

  # ─── AC-002 — missing external tool aborts early ─────────────

  Scenario: AC-002 scaffolder aborts cleanly when flutter is absent
    Given `flutter` is NOT on PATH
    When I run `/forge:init --archetype full-stack-monorepo demo-app --org com.example`
    Then the scaffolder exits with code 5
    And the error message contains "flutter not found on PATH"
    And no target directory is created

  # ─── AC-003 — flutter-create output is never mutated ─────────

  Scenario: AC-003 Forge overlay does not modify flutter-create output
    Given I have scaffolded `demo-app` via the archetype
    When I re-run the overlay with `--force` and a pinned SOURCE_DATE_EPOCH
    Then the SHA-256 of `demo-app/{.forge.yaml,Taskfile.yml,docker-compose.dev.yml,CLAUDE.md}` is byte-identical
    And no file under `demo-app/frontend/` generated by `flutter create` was modified

  # ─── AC-004 — buf lint passes out of the box ─────────────────

  Scenario: AC-004 scaffolded protos pass buf lint with zero warnings
    Given I have scaffolded `demo-app` via the archetype
    When I run `cd demo-app/shared/protos && buf lint`
    Then exit code is 0
    And stdout is empty (aside from warning suppression for PACKAGE_DIRECTORY_MATCH, which is documented in buf.yaml)

  # ─── AC-005 — integration harness detects missing file ───────

  Scenario: AC-005 scaffolded validator detects a missing contract file
    Given I have scaffolded `demo-app` via the archetype
    And I delete `demo-app/.forge/schemas/full-stack-monorepo/schema.yaml`
    When I run `FORGE_ROOT=demo-app bash demo-app/.forge/scripts/validate-foundations.sh`
    Then exit code is non-zero
    And stdout contains "FAIL: FR-GL-001 — schema file missing"

  # ─── AC-006 — integration harness detects contract drift ─────

  Scenario: AC-006 scaffolded validator detects contract drift (malformed version)
    Given I have scaffolded `demo-app` via the archetype
    And I mutate `demo-app/.forge/schemas/full-stack-monorepo/schema.yaml` to set `version: draft`
    When I run `FORGE_ROOT=demo-app bash demo-app/.forge/scripts/validate-foundations.sh`
    Then exit code is non-zero
    And stdout contains "FAIL: FR-GL-001 — version does not match SemVer"

  # ─── AC-007 — scaffold plan is parseable and complete ────────

  Scenario: AC-007 scaffold-plan.yaml is valid and references real files
    Given the archetype scaffold-plan exists at `.forge/templates/archetypes/full-stack-monorepo/scaffold-plan.yaml`
    When I parse it via `python3 -c "import yaml; yaml.safe_load(open(path))"`
    Then parsing succeeds
    And `templates:` has at least 20 entries
    And every `templates[].source` resolves to an existing file in the archetype tree
    And `official_scaffolders:` lists `flutter create` and 5 `cargo new` commands

  # ─── NFR-005 — idempotence under --force ─────────────────────

  Scenario: NFR-005 overlay is byte-idempotent with SOURCE_DATE_EPOCH pinned
    Given I have scaffolded `demo-app` via the archetype
    When I re-run `overlay.sh --target demo-app --force` with the same SOURCE_DATE_EPOCH
    Then the SHA-256 of every overlay-owned file is identical between the two runs

  # ─── NFR-006 — performance budget ────────────────────────────

  Scenario: NFR-006 scaffold completes within the budget
    Given flutter + cargo + buf are installed and on PATH
    When I time a full `init.sh` scaffold of `demo-app`
    Then the wall-clock duration is less than 60 seconds (hard ceiling)
    And SHOULD be less than 30 seconds on a warm cache
