// Audit: B.7.2 (b7-2-scaffolder, Phase 3) — ai-native-rag Connect-ES v2 client
// Structural precedent: full-stack-monorepo/2.0.0/frontend/web-public/src/lib/connect-client.ts.tmpl
// Standard: .forge/standards/web-frontend.yaml
//
// Connect-ES v2 browser client wiring. For a BROWSER/Qwik client the transport
// is createConnectTransport from @connectrpc/connect-web (NOT connect-node); the
// client factory is createClient from @connectrpc/connect. Both runtime pins are
// owned by transport.yaml (^2.0.0; single source of truth) and declared in
// package.json.
//
// The RagService descriptor is buf-generated by the es plugin
// (buf.build/bufbuild/es:v2.2.0, target=ts) into ./generated/connect/ from
// shared/protos/v1/rag/rag.proto. Connect v2 retired the separate *_connect file:
// the single protobuf-es v2 *_pb file carries BOTH the message types and the
// service descriptor. Run `task proto` (or `cd shared/protos && buf generate`) to
// materialise `rag_pb.ts` before this module type-checks / builds.
//
// Streaming (B.7.10): the default streaming transport is Connect server-streaming
// (SSE-class), consumed in the browser with `for await (const chunk of
// ragClient.queryStream(...))` over the SAME @connectrpc/connect-web transport
// (Context7 /connectrpc/connect-es, 2026-06-23). WebTransport is a documented
// forward alternative, NOT a Connect-ES transport (ADR-B7-10-005) — see README.
// The unary `query()` is RETAINED as the UI-layer XI.5 degradation target.
// NEVER PUT SECRETS HERE — the backend URL is injected via env, not committed.

import { createClient } from "@connectrpc/connect";
import { createConnectTransport } from "@connectrpc/connect-web";
// Generated by buf (es:v2.2.0, target=ts) from shared/protos/v1/rag/rag.proto.
// `RagService` is the GenService descriptor; QueryResponse is a plain message type.
import { RagService } from "./generated/connect/rag_pb";

// Backend Connect/HTTP base URL. Resolved from the Vite env at build/runtime;
// the LLM gateway (backend/llm_gateway) is the Connect endpoint. In production the
// request flows Qwik → Envoy Gateway (B.8.4) → llm-gateway → rag pipeline.
const baseUrl: string =
  import.meta.env.PUBLIC_API_URL ?? "http://localhost:8088";

const transport = createConnectTransport({ baseUrl });

/** Connect client for the RAG query service (one unary RPC: Query). */
export const ragClient = createClient(RagService, transport);

/** A single retrieved source chunk surfaced alongside the answer. */
export interface RagSource {
  documentId: string;
  content: string;
  score: number;
}

/** The shape the UI consumes — mirrors rag.v1.QueryResponse. */
export interface RagAnswer {
  answer: string;
  sources: RagSource[];
  /** True when the non-AI fallback produced the answer (Article XI.5). */
  fallbackUsed: boolean;
}

/**
 * Run one RAG query (unary). Returns the generated answer (or the non-AI
 * fallback) plus the grounding sources and the `fallbackUsed` flag, so the UI
 * can surface when the XI.5 fallback path was taken.
 */
export async function query(question: string, topK = 0): Promise<RagAnswer> {
  const res = await ragClient.query({ question, topK });
  return {
    answer: res.answer,
    // `s` is annotated against the local RagSource shape (mirrors rag.v1.SourceChunk)
    // so this file stays self-consistent before `task proto` generates rag_pb.
    sources: res.sources.map((s: RagSource) => ({
      documentId: s.documentId,
      content: s.content,
      score: s.score,
    })),
    fallbackUsed: res.fallbackUsed,
  };
}

/** One streamed answer frame — mirrors rag.v1.QueryChunk (B.7.10). */
export interface RagChunk {
  /** Incremental answer slice; empty on the one-shot sources frame / terminal. */
  tokenDelta: string;
  /** Grounding chunks — present on the one-shot sources frame. */
  sources: RagSource[];
  /** True on the single terminal frame that closes the stream. */
  done: boolean;
  /** True when the stream degraded to the non-AI fallback (Article XI.5). */
  fallbackUsed: boolean;
}

/**
 * Run one STREAMING RAG query (B.7.10). Returns an async iterable of answer
 * frames consumed with `for await (const chunk of queryStream(...))` — the
 * default streaming transport is Connect server-streaming (SSE-class) over the
 * same `@connectrpc/connect-web` transport as the unary `query()`. Pass an
 * `AbortSignal` (from an `AbortController`) so the caller can Stop the in-flight
 * stream / cancel-on-unmount (FR-B7-10-022): Connect threads `signal` into the
 * call and aborts the underlying fetch.
 *
 * Article XI.4: the caller subscribes to this stream (no blocking AI call).
 * Article XI.5: a `fallbackUsed` frame marks the non-AI degradation mid-stream.
 */
export async function* queryStream(
  question: string,
  topK = 0,
  signal?: AbortSignal,
): AsyncGenerator<RagChunk> {
  // Connect-ES v2: a server-streaming method is an async iterable; the second
  // arg is CallOptions, where `signal` wires browser cancellation.
  for await (const chunk of ragClient.queryStream({ question, topK }, { signal })) {
    yield {
      tokenDelta: chunk.tokenDelta,
      sources: chunk.sources.map((s: RagSource) => ({
        documentId: s.documentId,
        content: s.content,
        score: s.score,
      })),
      done: chunk.done,
      fallbackUsed: chunk.fallbackUsed,
    };
  }
}

/**
 * Exponential-backoff retry policy for transient stream errors (FR-B7-10-023).
 * Named, documented constants — NOT inline magic numbers. After `maxAttempts`
 * failed stream attempts the caller degrades to the unary `query()` path
 * (the UI-layer Article XI.5 fallback: SSE-class → unary → non-AI fallback).
 */
export interface RetryPolicy {
  /** Bounded number of stream attempts before degrading to unary. */
  readonly maxAttempts: number;
  /** Base delay (ms) for the first backoff. */
  readonly baseDelayMs: number;
  /** Upper bound (ms) on any single backoff (caps exponential growth). */
  readonly maxDelayMs: number;
}

/** The default exponential-backoff retry policy for the streaming UI. */
export const DEFAULT_RETRY_POLICY: RetryPolicy = {
  maxAttempts: 3,
  baseDelayMs: 250,
  maxDelayMs: 4000,
};

/**
 * The exponential backoff for `attempt` (0-based): `base * 2^attempt`, capped at
 * `maxDelayMs`. A named helper so the retry math is testable and free of inline
 * magic numbers (FR-B7-10-023).
 */
export function exponentialBackoffMs(attempt: number, policy: RetryPolicy = DEFAULT_RETRY_POLICY): number {
  const delay = policy.baseDelayMs * 2 ** attempt;
  return Math.min(delay, policy.maxDelayMs);
}
